### PR TITLE
Remove dated FAQs

### PR DESCRIPTION
**Pull request by timoman**
Remove jokes that were out of context and/or aren't great anymore.
Also remove possibly fradulent charity.

### CODE REVIEW

**Comment by alexandre-normand** [comment]
> Also remove possibly fradulent charity.

😬

**Comment by alexandre-normand** [comment]
Do you mind also updating the GitHub url to match what's going to be the new organisation name?

**Comment by timoman** [comment]
> Do you mind also updating the GitHub url to match what's going to be the new organisation name?
@alexandre-normand Nice catch. Updated.

**Comment by alexandre-normand** [comment]
This looks great. Thanks for taking care of it, @timoman.

**Pull request merged**
